CREATE TABLE Carrello(
	id_carrello INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	totale DECIMAL(10,2),
	cf_cliente VARCHAR(16),
	
	CONSTRAINT fk_carrello_cliente
		FOREIGN KEY (cf_cliente)
		REFERENCES cliente(codicefiscale)
		ON DELETE CASCADE
);