CREATE TABLE Certificato(
	cert_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	data_emissione DATE,
	data_scadenza DATE,
	tipo VARCHAR (50),
	percordo_file BYTEA,
	
	cf_Cliente VARCHAR(16) NOT NULL,
	CONSTRAINT fk_certificato_cliente
		FOREIGN KEY(cf_Cliente)
		REFERENCES cliente(codicefiscale)
)