CREATE TABLE Iscrizione(
	id_iscrizione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	id_cliente VARCHAR(16),
	CONSTRAINT fk_iscrizione_cliente
		FOREIGN KEY (id_cliente)
		REFERENCES cliente(codicefiscale)
		ON DELETE CASCADE
);