CREATE TABLE Lezione
(
	id_lezione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100),
	descrizione TEXT,
	giorno INT,
	ora_inizio TIME,
	ora_fine TIME,

	id_corso INT NOT NULL,

	CONSTRAINT fk_lezione_corso
		FOREIGN KEY(id_corso)
		REFERENCES Corso(id_corso)
		ON DELETE CASCADE
);