CREATE TABLE Prenotazione
(
	id_prenotazione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	stato_prenotazione VARCHAR(20),
	data_pren DATE,
	ora_pren TIME,
	
	id_lezione INT,
	cf_cliente VARCHAR(16),

	CONSTRAINT fk_prenotazione_lezione
		FOREIGN KEY (id_lezione)
		REFERENCES Lezione(id_lezione)
		ON DELETE CASCADE,

	CONSTRAINT fk_prenotazione_cliente
		FOREIGN KEY (cf_cliente)
		REFERENCES Cliente(codicefiscale)
		ON DELETE CASCADE
);