CREATE TABLE Prodotto(
	id_prodotto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	giacenza INT NOT NULL,
	nome VARCHAR(50),
	prezzo DECIMAL (10,2),
	id_carrello INT,

	CONSTRAINT fk_prodotto_carrello
		FOREIGN KEY(id_carrello)
		REFERENCES carrello(id_carrello)
		ON DELETE CASCADE
);